/** skill-icons short names mapped to simple-icons slugs */
export const SHORT_NAMES: Record<string, string> = {
  js: "javascript",
  ts: "typescript",
  py: "python",
  tailwind: "tailwindcss",
  vue: "vuedotjs",
  nuxt: "nuxt",
  go: "go",
  cf: "cloudflare",
  wasm: "webassembly",
  postgres: "postgresql",
  k8s: "kubernetes",
  next: "nextdotjs",
  mongo: "mongodb",
  md: "markdown",
  scss: "sass",
  sc: "scala",
  net: "dotnet",
  gatsbyjs: "gatsby",
  gql: "graphql",
  vlang: "v",
  express: "express",
  googlecloud: "googlecloud",
  mui: "mui",
  nest: "nestjs",
  ktorio: "ktor",
  rollup: "rollupdotjs",
  rxjs: "reactivex",
  rxjava: "reactivex",
  ghactions: "githubactions",
  sklearn: "scikitlearn",
  unreal: "unrealengine",
};

/** skill-icons icon IDs that differ from simple-icons slugs */
export const SLUG_ALIASES: Record<string, string> = {
  nodejs: "nodedotjs",
  vuejs: "vuedotjs",
  nuxtjs: "nuxt",
  nextjs: "nextdotjs",
  golang: "go",
  expressjs: "express",
  materialui: "mui",
  html: "html5",
  java: "openjdk",
  cpp: "cplusplus",
  bash: "gnubash",
  kafka: "apachekafka",
  threejs: "threedotjs",
  gcp: "googlecloud",
  rollupjs: "rollupdotjs",
  githubactions: "githubactions",
  scikitlearn: "scikitlearn",
  windi: "windicss",
  bots: "discordbots",
  amazonwebservices: "amazon",
  pwsh: "gnupowershell",
  ae: "adobeaftereffects",
  ai: "adobeillustrator",
  pr: "adobepremierepro",
  ps: "adobephotoshop",
  au: "adobeaudition",
};
