name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: avotokyo/workflows/release@12db9a20f28938660c79ad2899e3dad379f68d25
    with:
      publish: false
    permissions:
      contents: write
      id-token: write
