name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: avotokyo/workflows/.github/workflows/composite/release.yml@main
    with:
      publish: true
      type: github
      build: vp run build
    permissions:
      contents: write
      packages: write
      id-token: write
