name: Unit Test

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: avotokyo/workflows/.github/workflows/unit-test.yml@main
    with:
      build: ""
